version: '3.7'

services:
  api-nginx:
    image: nginx:latest
    container_name: api-nginx
    depends_on:
      - api-php
    ports:
      - "8005:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - portal

  api-php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api-mysql
    container_name: api-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000"
    networks:
      - portal

  api-mysql:
    image: "mysql:latest"
    container_name: api-mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: email-logger
    ports:
      - "3306"
    networks:
      - portal

  api-redis:
    image: "redis:alpine"
    container_name: api-redis
    command: redis-server --requirepass secret
    ports:
      - "6379"
    networks:
      - portal

networks:
  portal:
    driver: bridge
