name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Set up SSH key
        run: |
          echo "Host ${{ secrets.SERVER_ADDRESS }}" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "*"
          target: /var/www/html
          overwrite: true

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/deploy_key root@${{ secrets.SERVER_ADDRESS }} '
            cd /var/www/html &&
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan optimize:clear &&
            php artisan key:generate &&
            php artisan migrate --force &&
            php artisan storage:link &&
            php artisan config:cache &&
            php artisan route:cache
          '
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Adjust permissions and restart nginx
        run: |
          ssh -i ~/.ssh/deploy_key root@${{ secrets.SERVER_ADDRESS }} '
            sudo chmod -R 755 /var/www/html
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R ug+rwx /var/www/html/bootstrap/cache
            sudo chown -R www-data:www-data /var/www/html/storage
            sudo chmod -R ug+rwx /var/www/html/storage
            sudo systemctl restart nginx
          '
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
